server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:D:\Source_GIT\Other\MicroServices\springCloudConfigurationserver\src\main\resources\config\licensingservice